### ISSUE TITLE
ide support js language comment ?

### ISSUE THREAD

**Issue by qssq** [qtiuto/lua-for-android#1]
ide support js language comment ?

**Comment by qtiuto** [comment]
If you mean that whether the editor supports js or java style comment，it doesn't. Use lua style comment instead.@qssq

**Comment by qssq** [comment]
I found a lot of versions of textwarrior from the Internet, and I didn't find the answer. I can't display comments using the lua version.


//https://github.com/luoyesiqiu/simpleC/tree/master/app/src/main/java/com/myopicmobile/textwarrior/common
//https://github.com/LingSaTuo/CreateJS
//https://github.com/brnogz/TextWarriorLibrary
//https://github.com/qtiuto/lua-for-android english
//https://github.com/XsJIONG/VIDE
//https://github.com/fengdeyingzi/CodeEditor
//https://github.com/nirenr/AndroLua_pro

**Comment by qssq** [comment]
There is a part of the code inside.
Can't understand, don't know how to modify it to be compatible with js, realize // turn green
![hze b7t h6 f 7xnl 7n](https://user-images.githubusercontent.com/14260426/50400289-818b0e00-07c0-11e9-8aef-a86c4015dccc.jpg)


/**
* Translates characters to character classes
*/
Private static final String ZZ_CMAP_PACKED =
    "\11\0\1\1\1\2\1\66\1\66\1\3\22\0\1\1\1\44\1\41" +
    "\1\43\1\0\1\51\1\0\1\42\1\53\1\54\1\50\1\10\1\60" +
    "\1\16\1\14\1\52\1\11\11\6\1\62\1\61\1\46\1\15\1\45" +
    "\2\0\4\13\1\7\1\13\21\5\1\12\2\5\1\4\1\64\1\55" +
    "\1\63\1\5\1\0\1\17\1\22\1\34\1\21\1\24\1\32\1\5" +
    "\1\37\1\31\1\5\1\25\1\27\1\5\1\20\1\26\1\36\1\5" +
    "\1\23\1\30\1\35\1\33\1\65\1\40\1\12\2\5\1\56\1\0" +
    "\1\57\1\47\6\0\1\66\u1fa2\0\1\66\1\66\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ Uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

/**
* Translates characters to character classes
*/
Private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

/**
* Translates DFA states to action switch labels.
*/
Private static final int [] ZZ_ACTION = zzUnpackAction();

**Comment by qssq** [comment]
can you hellp me?  😔

**Comment by qtiuto** [comment]
Long comment in lua is this style `--[[  this comment can be multi-line ]]`, and short comment starts with `--coment`. @qssq

**Comment by qssq** [comment]
I know, I mean, I want to change it to js ide, then support // and /**/, I am having problems and can’t start.

**Comment by qtiuto** [comment]
It's not an easy task to convert the lua lexer to js lexer cause its definition is hard to change and many attributes is hard coded. I suggest you finding out another proper lexer to do so. Actually, I just copy the editor from another project for short. @qssq
