### ISSUE TITLE
Failed to resolve: luadroid:dexmaker:unspecified

### ISSUE THREAD

**Issue by fly2012** [qtiuto/lua-for-android#2]
I got this error message.

**Comment by qtiuto** [comment]
This is because of my upload mistakes, I will fix it in the next version.
The existed version actually have some bugs. I will also fix them in the next version.
proxy syntax will also change in the next version to meet some need. And vararg syntax call also be supported. I'm still testing. @fly2012

**Comment by fly2012** [comment]
That't great!Thanks!
